### ISSUE TITLE
Box-drawing characters

### ISSUE THREAD

**Issue by vanillajonathan** [minhhungit/ConsoleTableExt#4]
It could print the table using [box-drawing characters](https://en.wikipedia.org/wiki/Box-drawing_character).

    ┌───────┬─────┐
    │ Name  │ Age │  
    ├───────┼─────┤
    │ Alice │  10 │
    │ Bob   │  20 │    
    │ Clare │  30 │    
    └───────┴─────┘

**Comment by minhhungit** [comment]
Hi @vanillajonathan 
Unlucky currently we don't support box-drawing characters, but I will try to implement it in future when I have more time.
Thank you for your suggestion.
btw, if you have PR, I will be very happy to accept it

**Comment by minhhungit** [comment]
@spreedated thank you, I'm reviewing it, LGTM

**Comment by minhhungit** [comment]
I think the solution to support this feature is we have to define a map of 'char' of delimiter and divider, like top left, top middle, top right ... by that way developer can enter whatever they want, here are positions. 

![image](https://user-images.githubusercontent.com/2279508/105085852-f11c7600-5aca-11eb-86b7-7576ba2f8fb2.png)

**Comment by minhhungit** [comment]
By creating a map we can support these formats

![image](https://user-images.githubusercontent.com/2279508/105087036-76545a80-5acc-11eb-9e3c-731f04d30951.png)

**Comment by spreedated** [comment]
Good point, we can support this plus adding some predefined "styles"? I doubt people like to map everytime, however the "map" idea is good :)

**Comment by minhhungit** [comment]
>plus adding some predefined "styles"

yes we will "pre-define" current formats like Markdown, Alternative, FrameDoublePip... using the map

**Comment by minhhungit** [comment]
This is map I think

![image](https://user-images.githubusercontent.com/2279508/105103242-d81fbf00-5ae2-11eb-80f7-cc8902f931df.png)

Not: we also should try to open a way that help developer overwrite existed "Format defination", so we can support table header which has difference style, like this
```
╔═════════════╗
║ I Am Header ║
╠═════════════╣
║    xyz      ║
╟─────────────╢
║    xyz      ║
╙─────────────╜
```

**Comment by minhhungit** [comment]
WIP

![image](https://user-images.githubusercontent.com/2279508/105289561-bd387200-5bea-11eb-8059-9ada07a41bf3.png)

**Comment by vanillajonathan** [comment]
Maybe it would be nice if the first row (the header row), the one containing Name, Position, Office, Age, and Start Date had a double line under it and the second row (the first real data row).

**Comment by minhhungit** [comment]
@vanillajonathan you mean like this ?

![image](https://user-images.githubusercontent.com/2279508/105335456-a43fb900-5c0a-11eb-916e-f71529ac320a.png)

I'm working on it, almost done, I'm waiting PR from @spreedated first

**Comment by vanillajonathan** [comment]
@minhhungit Yes! 👍

**Comment by vanillajonathan** [comment]
Now imagine if the header text (Name, Position, Office, Age, and Start Date) could be written in a different [foreground color](https://docs.microsoft.com/en-us/dotnet/api/system.console.foregroundcolor?view=net-5.0) using the [`ConsoleColor`](https://docs.microsoft.com/en-us/dotnet/api/system.consolecolor?view=net-5.0) enum.

```cs
Console.ForegroundColor = ConsoleColor.White;
Console.Write("Name");
Console.ResetColor();
```

**Comment by spreedated** [comment]
Console color is a bit problematic, since not all consoles support this and there are different colorcodes, and you get those codes into your string output, e.g. Debug.Print or just string data to be saved in logfiles etc. - however, make it optional is always a good idea :)

**Comment by minhhungit** [comment]
version 3.0.0 is released, now we support box-drawing character, thanks all !
