### ISSUE TITLE
Could not install ConsoleTableExt from the NuGet tool

### ISSUE THREAD

**Issue by lonchanick** [minhhungit/ConsoleTableExt#41]
Hi, thanks for your job.

On VSC, I tried to install this extension from the NuGet tool console
>> Install-Package ConsoleTableExt
 
And I got this:
>> Error   Package restore failed. Rolling back package changes for 'ConsoleTableExt'. 
>>Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1108	Cycle detected. 
  ConsoleTableExt -> ConsoleTableExt (>= 3.2.0).	ConsoleTableExt	D:\.NET FOLDER\C# ACADEMY\Projects\ConsoleTableExt\ConsoleTableExt.csproj	1	

Thanks :D!

**Comment by minhhungit** [comment]
@lonchanick try to use this command: 
```
NuGet\Install-Package ConsoleTableExt -Version 3.2.0
```

Check more here https://www.nuget.org/packages/ConsoleTableExt/3.2.0

**Comment by minhhungit** [comment]
Or installing it manual using [NuGet Package Manager](https://learn.microsoft.com/en-us/nuget/consume-packages/install-use-packages-visual-studio)

**Comment by lonchanick** [comment]
Ok Thanks!
