### ISSUE TITLE
Is there a way to center the tables inside the console?

### ISSUE THREAD

**Issue by GuyMeuris** [minhhungit/ConsoleTableExt#6]
Maybe I missed it inside your code, but is there a way to center the tables inside the console?

Just have a use case for it at the moment...

THX for any comment on this.
Great job with the package BTW, luv it!

Greetings from Belgium,
Guy

**Comment by minhhungit** [comment]
Hi @GuyMeuris, at this time there is no feature like that, but the idea is awesome, I will research it

**Comment by minhhungit** [comment]
@GuyMeuris  You can do it like this:
```csharp
var strBuilder= ConsoleTableBuilder.From(SampleListData).Export();

var lines = strBuilder.ToString().Split('\n');
foreach (var line in lines)
{
    Console.WriteLine(String.Format("{0," + ((Console.WindowWidth / 2) + (line.Length / 2)) + "}", line));
}
```

Result:

![image](https://user-images.githubusercontent.com/2279508/105444125-dbac7500-5c9f-11eb-8e7e-7650080ec1da.png)

**Comment by minhhungit** [comment]
And align right 

Console.WriteLine(String.Format("{0," + Console.WindowWidth + "}", new string(' ', Console.WindowWidth - line.Length) + line));
